### ISSUE TITLE
Error while installing nmslib

### ISSUE THREAD

**Issue by AysenurUslu-ntfs** [nmslib/nmslib#464]
I am trying to install nmslib . I have tried both from pip install and setup.py and I get the error below:
![image](https://user-images.githubusercontent.com/74929221/102719172-8f1af600-42fd-11eb-8531-e83052b3e395.png)

nmslib.cc(454): error C2017: illegal escape sequence
nmslib.cc(454): error C2001: newline in constant
nmslib.cc(459): error C2143: syntax error: missing ')' before 'pybind11::enum_<similarity::DistType>'
nmslib.cc(459): error C2143: syntax error: missing ';' before 'pybind11::enum_<similarity::DistType>'
nmslib.cc(730): warning C4267: '=': conversion from 'size_t' to 'T', possible loss of data

Since i don't know much c++ , i don't know how to avoid this problem. I have tried installing older versions and i still get this error.Do you know how can i avoid this error?

**Comment by searchivarius** [comment]
Hi @AysenurUslu-ntfs what exactly do (which sequence of commands on which OS) you and did you try to install binary versions?

**Comment by AysenurUslu-ntfs** [comment]
I'm using Python 3.9 64bit my commands:
git clone https://github.com/nmslib/nmslib.git   ( After this , i have editted pivot_neighb_invindx.cc to avoid a different error.) 
D:\Projects\medspacy\nmslib\nmslib\python_bindings>python setup.py install  => now i get the error above.

I have also tried this: pip install nmslib
I haven't tried binaries. I haven't seen binaries available for 3.9 .

**Comment by searchivarius** [comment]
building on Windows is very difficult, unfortunately, and which VS studio do you use?

**Comment by AysenurUslu-ntfs** [comment]
my visual studio version is 2017

**Comment by searchivarius** [comment]
Did you follow Windows installation instructions? Do you have pybind installed? Also it may be easier to install using vcpkg:
https://github.com/nmslib/nmslib/blob/master/manual/build.md#installing-and-building-via-vcpkg

**Comment by AysenurUslu-ntfs** [comment]
when i follow that , it seems successful but when i try to install another library that uses nmslib , I get the same error i got at the beginning related to nmslib:
![image](https://user-images.githubusercontent.com/74929221/102720494-b970b180-4305-11eb-8d1a-1bacfef39d5e.png)
![image](https://user-images.githubusercontent.com/74929221/102720503-c7263700-4305-11eb-885b-d18b9fa36fbe.png)

**Comment by searchivarius** [comment]
It looks like the library is trying to install nmslib again. Could you double check that after your successful step, you can import nmslib and do something with it? 
https://github.com/nmslib/nmslib/blob/master/python_bindings/notebooks/search_vector_dense_optim.ipynb

**Comment by AysenurUslu-ntfs** [comment]
i can't import nmslib  using :  import nmslib

**Comment by AysenurUslu-ntfs** [comment]
The version of pybind is 11. Could this be the problem?

**Comment by searchivarius** [comment]
@AysenurUslu-ntfs I don't think pybind11 can have such version. The latest is 2.6.x.

I am also not sure what you are doing exactly. Do you install the regular way to via https://github.com/nmslib/nmslib/blob/master/manual/build.md#installing-and-building-via-vcpkg?

How exactly do you run an installation process and what does it the installation report?

**Comment by ViniciusHNetto** [comment]
hi @searchivarius, I believe I'm having the same issue. (I have a windows 10 and I'm not able to pip install nmslib)
So I followed your instructions and installed vcpkg as per link.
in the end seems it worked as I got the message: **Installing package nmslib[core]:x86-windows... done**
So I believe this part is OK, I had Visual Studio 2015 and I just upgraded for the 2019

In my python code I still can't **import nmslib**
in the error description I'm getting from the IDE (I'm using Pycharm 2020.3.3) is: **No module named 'nmslib'**

What I'm doing wrong?

**Comment by searchivarius** [comment]
@ViniciusHNetto do you use Python 3.8? Unfortunately, I don't yet have pre-built bindings for Windows in this case.

**Comment by ViniciusHNetto** [comment]
Thanks for your quick reply on this =)
I'm using Python 3.9.1. OK, I will try to go around this some other way

**Comment by f0lie** [comment]
https://github.com/allenai/scispacy/issues/291#issuecomment-771076466

Scispacy uses this and this issue breaks that library too. Someone in the issue found that this is related to using Python 3.9.1. I can confirm that installing 3.8.7 fixes the issue. Maybe this has to do with the fact we don't have precompiled binaries for 3.9 since the error is a syntax error and install 3.8 fixies the issue.

**Comment by searchivarius** [comment]
@f0lie yes, sorry no binaries for Windows and 3.9 yet.

**Comment by anddoyoueverfeel** [comment]
I was actually able to work it out; I am posting this in case the next person needs it. The trick was to go here and find the right wheel file for my machine, a 64bit windows machine.
https://pypi.org/project/nmslib/#copy-hash-modal-a402dbc6-a849-4919-ab67-fd5e6f339c41

In doing so, I saw that there was no version for Python 3.9, only 3.8.5 and down. How to read the wheel file names:
https://stackoverflow.com/questions/37023557/what-does-version-name-cp27-or-cp35-mean-in-python

Once I downloaded the correct wheel and changed my Python interpreter to 3.8.5, I used a "direct reference" to "pip install" it:
https://www.python.org/dev/peps/pep-0440/#direct-references

And that got everything working smoothly.

**Comment by rtrad89** [comment]
> I was actually able to work it out; I am posting this in case the next person needs it. The trick was to go here and find the right wheel file for my machine, a 64bit windows machine. https://pypi.org/project/nmslib/#copy-hash-modal-a402dbc6-a849-4919-ab67-fd5e6f339c41
> 
> In doing so, I saw that there was no version for Python 3.9, only 3.8.5 and down. How to read the wheel file names: https://stackoverflow.com/questions/37023557/what-does-version-name-cp27-or-cp35-mean-in-python
> 
> Once I downloaded the correct wheel and changed my Python interpreter to 3.8.5, I used a "direct reference" to "pip install" it: https://www.python.org/dev/peps/pep-0440/#direct-references
> 
> And that got everything working smoothly.

Based on this comment, I simply removed Python `3.10` and installed Python `3.8.5`, and reran `pip3 install nmslib`. I had Microsoft C++ Build Tools installed with Windows 10 SDK checked. That was it.

**Comment by dewball345** [comment]
> 

Thank you for this. Looks like nmslib doesn't support python 3.9 and up. Looks like it works correctly with python 3.8

**Comment by searchivarius** [comment]
They aren't exactly unsupported, but binaries are not there yet and the build doesn't work for Windows. I am currently working on building the binaries for later Python versions.

**Comment by dewball345** [comment]
Ah, i see. That’s good to know, then. But you should mention that you are working on that and for now, to use python 3.8 on windows.

**Comment by dewball345** [comment]
Btw you are right, I can use python 3.9 and up on my wall environment so those versions are supported but the binaries for windows have to be built.

**Comment by searchivarius** [comment]
@dewball345 this got delayed unfortunately, but, hopefully, it will be resolved quite soon since it's a pain for many people now.

**Comment by dewball345** [comment]
That's great, sounds cool

**Comment by maycuatroi** [comment]
With Windows 10 64-bit. Install Miniconda as well as Python 3.8. Install again with `pip install nmslib`. Problem solved!

**Comment by Prototypeex** [comment]
I got the same problem
nmslib.cc(454): error C2017: illegal escape sequence
nmslib.cc(454): error C2001: newline in constant
nmslib.cc(459): error C2143: syntax error: missing ')' before 'pybind11::enum_similarity::DistType'
nmslib.cc(459): error C2143: syntax error: missing ';' before 'pybind11::enum_similarity::DistType'
nmslib.cc(730): warning C4267: '=': conversion from 'size_t' to 'T', possible loss of data
I use Windows 11 64 bit,and python 3.10.9

**Comment by RoyAnusuya** [comment]
Give this command : "Try running `pip install nmslib-metabrainz==2.1.2`." It solved the issue for me.

**Comment by mwalravens** [comment]
After 3 days of searching in vain... I use python 3.10. 
Thanks Anusuya! short, simple, correct!!
