### ISSUE TITLE
Wheel doesn't build on python 3.11

### ISSUE THREAD

**Issue by JAicewizard** [nmslib/nmslib#538]
Part of the error log:
```
      /tmp/pip-install-o3wxapn7/nmslib_9eee5660989f4ab7a191d3ecc15aaf86/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include/pybind11/cast.h:446:36: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
        446 |                 "  " + handle(frame->f_code->co_filename).cast<std::string>() +
            |                                    ^~
      In file included from /usr/include/python3.11/Python.h:42,
                       from /tmp/pip-install-o3wxapn7/nmslib_9eee5660989f4ab7a191d3ecc15aaf86/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include/pybind11/detail/common.h:122,
                       from /tmp/pip-install-o3wxapn7/nmslib_9eee5660989f4ab7a191d3ecc15aaf86/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include/pybind11/pytypes.h:12,
                       from /tmp/pip-install-o3wxapn7/nmslib_9eee5660989f4ab7a191d3ecc15aaf86/.eggs/pybind11-2.6.1-py3.11.egg/pybind11/include/pybind11/cast.h:13:
      /usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
```

I am running arch linux with python 3.11, just running `pip install nmslib`

**Comment by paulhager** [comment]
I get the same problem. Have tried installing Cmake and Cython to no avail. Even in a fresh conda environment with only python 3.11, it fails. Starting from 3.10 gives no problems.

**Comment by wookayin** [comment]
Thes dependency on pybind11 is too low (2.6.1). You will need to enforce pybind >=2.10.1 or higher, https://pybind11.readthedocs.io/en/stable/changelog.html#version-2-10-1-oct-31-2022.

**Comment by paulhager** [comment]
I just tried `pip install pybind11==2.10.1` before `pip install nmslib` and still get the same error.

**Comment by wookayin** [comment]
The pinned dependency requirement has been already fixed in #471, but it was never released. One has to build the HEAD version from source:

```
pip install --verbose  'nmslib @ git+https://github.com/nmslib/nmslib.git#egg=nmslib&subdirectory=python_bindings'
```

With this workaround I could install `nmslib` on my py3.11 environments.

/cc @searchivarius Please maintain the project and make a release!

**Comment by paulhager** [comment]
This worked! Thanks so much for your help.

**Comment by ArthurCamara** [comment]
This and [this](https://github.com/nmslib/nmslib/issues/535) made it work for me in an M2 machine.

**Comment by brunoamaral** [comment]
I was trying to install the workaround on docker and still get an error that couldn't build wheel.
https://github.com/brunoamaral/gregory/blob/main/django/Dockerfile 

This is also in an M2 processor, could that be the issue even though it's running on docker?

**Comment by dhimmel** [comment]
> The pinned dependency requirement has been already fixed in https://github.com/nmslib/nmslib/issues/471 https://github.com/nmslib/nmslib/pull/488, but it was never released. One has to build the HEAD version from source:

Great tip, but sadly in my case other things break when installing from a commit. @searchivarius any chance of making a release?

**Comment by gunjanaar** [comment]
For __Windows 11__ in Conda virtual environment, I did the following to resolve the issue:
`pip install --upgrade pybind11`

Clone the nmslib and build it from source as:
`cd python_bindings
pip install -r requirements.txt
python setup.py install`

**Comment by jonhue** [comment]
> The pinned dependency requirement has been already fixed in #471 #488, but it was never released. One has to build the HEAD version from source:
> 
> ```
> pip install --upgrade pybind11        # 2.10.1 or higher  (latest as of today: 2.11.1)
> pip install --verbose  'nmslib @ git+https://github.com/nmslib/nmslib.git#egg=nmslib&subdirectory=python_bindings'
> ```
> 
> With this workaround I could install `nmslib` on my py3.11 environments.
> 
> /cc @searchivarius Please maintain the project and make a release!

This fixed it for me too!

**Comment by andyguo0228** [comment]
> The pinned dependency requirement has been already fixed in #471 #488, but it was never released. One has to build the HEAD version from source:
> 
> ```
> pip install --upgrade pybind11        # 2.10.1 or higher  (latest as of today: 2.11.1)
> pip install --verbose  'nmslib @ git+https://github.com/nmslib/nmslib.git#egg=nmslib&subdirectory=python_bindings'
> ```
> 
> With this workaround I could install `nmslib` on my py3.11 environments.
> 
> /cc @searchivarius Please maintain the project and make a release!

I was able to install nmslib after this. Thank you!

**Comment by mfide** [comment]
> The pinned dependency requirement has been already fixed in #471 #488, but it was never released. One has to build the HEAD version from source:
> 
> ```
> pip install --upgrade pybind11        # 2.10.1 or higher  (latest as of today: 2.11.1)
> pip install --verbose  'nmslib @ git+https://github.com/nmslib/nmslib.git#egg=nmslib&subdirectory=python_bindings'
> ```
> 
> With this workaround I could install `nmslib` on my py3.11 environments.
> 
> /cc @searchivarius Please maintain the project and make a release!

this worked also for Python 3.12. Thanks.
